### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by tahuana**
Change size of the "box" in the first page (making a little bit higher to get margin around the buttons), and align the search button with the rate buttons.

### CODE REVIEW

**Comment by katiedavis** [comment]
Why does this have everyone’s commits on it?

**Comment by martakule** [comment]
Oh, so it's not normal to have them all? I clicked on the last one and saw the actual change, but I was also wondering. Maybe from a large rebase?

**Comment by tahuana** [comment]
I don't know why... I did a pull upstream master and then create my local branch.

**Comment by katiedavis** [comment]
Hm. I guess it’s okay if all these commits have been merged to master

**Comment by rosexw** [comment]
You're merging it into bridge-school:styling, not bridge-school:master. That's why the left column in files changed is outdated, and the right column has everyone's commits and yours. 
For everyone -don't forget to squash all commits when merging!

**Comment by tahuana** [comment]
you are right rose! I changed it!

**Pull request merged**
